### ISSUE TITLE
cannot get nfts by owner

### ISSUE THREAD

**Issue by pashupatisah112** [primenumsdev/solana-nft-tools#3]
Basically 'getNFTsByOwner' function is not working properly. Also when, per page value is greater than 1, it fails

**Comment by primenumsdev** [comment]
Hi @pashupatisah112 Can you post an example with wallet address where it does failing, so I can reproduce?

**Comment by pashupatisah112** [comment]
[image: image.png]
This is how I am sending request. When the value or perPage is more than 1,
it throws following error.

[image: image.png]

**Comment by primenumsdev** [comment]
@pashupatisah112 I don't see images you attached, can you pls do it via GitHub web site.

**Comment by pashupatisah112** [comment]
I have created an issue in your repo. I have attached those missing files
in this email.

**Comment by pashupatisah112** [comment]
![request](https://user-images.githubusercontent.com/55347604/148249045-edb0efce-c7dc-4fd7-8d70-b749a7705ae9.png)
![response](https://user-images.githubusercontent.com/55347604/148249049-6e288d67-05da-4775-855a-9bf84eaa75ad.png)

**Comment by primenumsdev** [comment]
what is the value of `this.walletAddress` when the error happens? Because this can be caused by the specific token with invalid meta data, also what net are you using? mainnet-beta, devnet? I need this information to be able reproduce the error you have.

**Comment by pashupatisah112** [comment]
this.walletAddress is my phantom wallet address and the error is same in both mainnet-beta and devnet.

**Comment by pashupatisah112** [comment]
correction.. mainnet-beta is fine. but problem in devnet
![image](https://user-images.githubusercontent.com/55347604/148254567-aa368aa6-8e13-4ee5-907e-388ef17743b9.png)

**Comment by primenumsdev** [comment]
So the mint addresses belongs to specific net, if it exists in mainnet, it's not the same on devnet.

**Comment by pashupatisah112** [comment]
Hey, can you please help me with your code. I could not figured out myself. Let me know if we can have a real-time conversation when you are online.

**Comment by primenumsdev** [comment]
Hey @pashupatisah112 sorry, I am not available for real-time conversation.
