### ISSUE TITLE
"fetch is not a function" error when trying to get nft metadata using getNFTByMintAddress

### ISSUE THREAD

**Issue by shreyvijayvargiya** [primenumsdev/solana-nft-tools#6]

**Comment by shreyvijayvargiya** [comment]
Need help regarding the same, I need to fetch NFTs metadata from the mint token address but I am getting an error as fetch is not a function?. 
I have this doubt that since the package has the dependency on node-fetch so will it won't work in react applications?

**Comment by shreyvijayvargiya** [comment]
Hello any update on this ?

**Comment by primenumsdev** [comment]
Hi @shreyvijayvargiya,

Yes you are right, the library can work only on the backend at the moment.
Currently, I don't have time to work on it, but PR's are welcome.

Thank you!
